### ISSUE TITLE
datetimepicker error

### ISSUE THREAD

**Issue by brendan-w** [brendanwhitfield/midas#22]
```
TypeError: $(...).datetimepicker is not a function
```

After editting a task/job and clicking the `Save Job` button. A `git bisect` revealed:

```
f119f95545e0c22acb2396e249080db88ac227c8 is the first bad commit
commit f119f95545e0c22acb2396e249080db88ac227c8
Author: Brendan Whitfield <brendanw@windworksdesign.com>
Date:   Fri Jul 10 13:02:48 2015 -0400

    purging unnecessary fields/views from the project page

:040000 040000 c715c7d09b027d7744bc56ea021b9cdcd8758b55 452a0cae84faf671161f4783f8e1fee7973a4bf7 M  assets
```
